//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credit
    {
        public int CreditID { get; set; }
        public string Name { get; set; }
        public string CompanyName { get; set; }
        public string UsedIn { get; set; }
        public string URL { get; set; }
    }
}
